# Generated by Django 6.0.5 on 2026-05-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(help_text='The original long URL submitted by the user.', max_length=2000)),
                ('short_code', models.CharField(db_index=True, help_text='The unique short code generated for this URL.', max_length=15, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.')),
                ('click_count', models.PositiveIntegerField(default=0, help_text='Tracks how many times this short URL has been visited.')),
            ],
            options={
                'verbose_name': 'URL',
                'verbose_name_plural': 'URLs',
                'ordering': ['-created_at'],
            },
        ),
    ]
